django_pet_project/cart/urls.py
from django.urls import path


from . views import (
    cart_add,
    cart_detail,
    cart_remove
)


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

django_pet_project/cupons/urls.py
from django.urls import path
from .views import cupon_apply


app_name = 'cupons'

urlpatterns = [
    path('apply', cupon_apply, name='apply')
]

django_pet_project/django_pet_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django_pet_project import settings
from cart import views
from shop import views
from users import views as user_views
from contact_form.views import create


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact_form/', include('contact_form.urls', namespace='contact_form')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('foto_gallery/', include('foto_gallery.urls', namespace='foto_gallery')),
    path('', include('shop.urls')),
    
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_pet_project/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
         name='admin_order_detail'),
    path('admin/order/(<int:order_id>)/pdf/', views.admin_order_PDF,
         name='admin_order_PDF')
]

django_pet_project/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop.views import (
    product_list, 
    product_detail,
    home,   
    oplata,
    contacts,
)

app_name = 'shop'

urlpatterns = [
    path('',home, name='home'),
    path('list', product_list, name='product_list'),
    path('<str:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('oplata', oplata, name='oplata'),
    path('contacts', contacts, name='contacts'),
    


]


# path('', views.product_list, name='product_list'),
#     path('elasticsearch_results/', ElasticSearchView.as_view(), name='elasticsearch'),
#     path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<str:brand_slug>', views.brands_views, name='brands_views'),
#     path('<str:id>/<str:slug>/', views.product_detail, name='product_detail'),
# path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<str:brand_slug>', views.brands_views, name='brands_views'),
#     path('<str:id>/<str:slug>/', views.product_detail, name='product_detail'),


# urlpatterns = [
#     url(r'^$', views.product_list, name='product_list'),
#     url(r'^(?P<category_slug>[-\w]+)/$',
#         views.product_list,
#         name='product_list_by_category'),
#     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
#         views.product_detail,
#         name='product_detail'),
# ]

django_pet_project/cart/models.py
from django.db import models

# Create your models here.

django_pet_project/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

django_pet_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from cupons.forms import CuponApllyForm
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    cupon_apply_form = CuponApllyForm()
    return render(request, 'cart/detail.html',
                  {'cart': cart, 'cupon_apply_form': cupon_apply_form})

django_pet_project/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
Ваша корзина товаров
{% endblock %}

{% block content %}

<div class="container">
    <div class="row" style="margin-top: 4%">
        <table class="table table-dark table-hover">
            <thead>
                <tr>

                    <th scope="col">Изображение</th>
                    <th scope="col">№</th>
                    <th scope="col">Товар</th>
                    <th scope="col">Кол-во</th>
                    <th scope="col">Удалить</th>
                    <th scope="col">Цена одного товара</th>
                    <th scope="col">КУПОН</th>
                    {% if cart.cupon and cart.cupon.active and cart.cupon.valid_to %}
                    <th scope="col">СКИДКА -{{ cart.cupon.discount }}%</th>
                    <th scope="col">ИГОГО со СКИДКОЙ </th>
                    {% else %}
                    <th scope="col">ИГОГО</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}

                <tr>

                    <th scope="row">
                        <a href="{{ product.get__absolute_url }}">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                alt="..." style="height: 130px; width: auto">
                        </a>
                    </th>
                    <td style="width: 15px;">{{ forloop.counter }}</td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {% csrf_token %}
                            <span style="display:inline-block">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input type="submit" value="Изменить" class="btn btn-outline-info"
                                    style="margin-top:-1%;">
                            </span>
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                    </td>
                    <td> {{ item.price }}</td>
                    <td>
                        <form action="{% url 'cupon:apply' %}" method="post" class="add">
                            {% csrf_token %}
                            <fieldset class="form-group">

                                <!-- {{ cupon_apply_form|join:"" }} -->
                                {{ cupon_apply_form|crispy }}
                            </fieldset>

                            <div class="form-group button_section">
                                <input class="button_base blue_button" type="submit" value="Применить">
                            </div>
                        </form>

                    </td>
                    {% if cart.cupon and cart.cupon.active and cart.cupon.valid_to %}
                    <td> -{{ cart.get_discount|floatformat:"2" }} </td>
                    <td>{{ cart.get_total_price_after_discount|floatformat:"2" }}</td>
                    {% else %}
                    <td>{{ cart.get_total_price }}</td>
                    {% endif %}

                </tr>
                {% endwith %}
                {% endfor %}
                <tr>
                    <td><b>Суммa:</b></td>
                    {% if cart.cupon and cart.cupon.active and cart.cupon.valid_to %}
                    <td colspan="7"></td>
                    <td colspan="num"><b></b>{{ cart.get_total_price_after_discount|floatformat:"2" }}</b></td>
                    {% else %}
                    <td colspan="6"></td>
                    <td colspan="num"><b> {{ cart.get_total_price }}</b></td>
                    {% endif %}


                </tr>

            </tbody>
        </table>

        </tbody>
        </table>
        <p class="text-right">
            <a href="{% url 'shop:product_list' %}" class="btn btn-default">Продолжить покупку</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Оформить заказ</a>
        </p>

    </div>
</div>

{% endblock %}