django_pet_project/cart/urls.py
from django.urls import path


from . views import (
    cart_add,
    cart_detail,
    cart_remove
)


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

django_pet_project/django_pet_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django_pet_project import settings
from cart import views
from shop import views
from users import views as user_views
from contact_form.views import create


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact_form/', include('contact_form.urls', namespace='contact_form')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('foto_gallery/', include('foto_gallery.urls', namespace='foto_gallery')),
    path('', include('shop.urls')),
    
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_pet_project/feedback/urls.py
from django.urls import path


from .views import create, feedback_form


app_name = 'feedback'

urlpatterns = [
    path('feedback_form', feedback_form, name='feedback_form'),
    path('feedback', create, name='feedback'),
    
]

django_pet_project/foto_gallery/urls.py
from django.urls import path


from .views import create


app_name = 'foto_gallery'

urlpatterns = [
    path('foto_gallery', create, name='foto_gallery'),
    
]

django_pet_project/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop.views import (
    product_list, 
    product_detail,
    home,   
    oplata,
    contacts,
)

app_name = 'shop'

urlpatterns = [
    path('',home, name='home'),
    path('list', product_list, name='product_list'),
    path('<str:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('oplata', oplata, name='oplata'),
    path('contacts', contacts, name='contacts'),
    


]


# path('', views.product_list, name='product_list'),
#     path('elasticsearch_results/', ElasticSearchView.as_view(), name='elasticsearch'),
#     path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<str:brand_slug>', views.brands_views, name='brands_views'),
#     path('<str:id>/<str:slug>/', views.product_detail, name='product_detail'),
# path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<str:brand_slug>', views.brands_views, name='brands_views'),
#     path('<str:id>/<str:slug>/', views.product_detail, name='product_detail'),


# urlpatterns = [
#     url(r'^$', views.product_list, name='product_list'),
#     url(r'^(?P<category_slug>[-\w]+)/$',
#         views.product_list,
#         name='product_list_by_category'),
#     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
#         views.product_detail,
#         name='product_detail'),
# ]

django_pet_project/users/urls.py
from django.urls import include, path

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('page_ordered_goods/', views.page_ordered_goods,
         name='page_ordered_goods'),
    path('change_phone_or_image/', views.change_phone_or_image,
         name='change_phone_or_image'),
]

django_pet_project/shop/models.py
import os
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    images = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True)
    pris = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлен")


    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])

def get_upload_path(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return os.path.join('images/', filename)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products',
        verbose_name="Категория",
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=100, db_index=True)
    features = models.TextField(blank=True, verbose_name="Характеристики")  # Empty value
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                verbose_name="Цена")
    available = models.BooleanField(default=True, verbose_name="Наличие")
    stock = models.PositiveIntegerField(verbose_name="Количество")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    image = models.ImageField(upload_to=get_upload_path, blank=True,
                              verbose_name="Изображение товара")

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        
    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

django_pet_project/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.http import HttpResponse

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    search_query = request.GET.get('search', '')

    if search_query:
        products = Product.objects.filter(
            Q(name__icontains=search_query) |
            Q(description__icontains=search_query))
        paginator = Paginator(products, len(products) or 100)
    else:
        paginator = Paginator(products, 12)

    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()

    # if page.has_previous():
    #     prev_url = '?page={}'.format(page.previous_page_number())
    # else:
    #     prev_url = ''
    
    # if page.has_next():
    #     next_url = '?page={}'.format(page.next_page_number())
    # else:
    #     next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        # 'next_url': next_url,
        # 'prev_url': prev_url,
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

def home(request):
    categories = Category.objects.all()
    list_foto = [{'imag':'54865518_2.jpg','nam':'Фруктовый'},
                {'imag':'54857587_2.jpg','nam':'Для девочек'},
                {'imag':'54883095_2.jpg','nam':'Десерт'},
                {'imag':'54868104_2.jpg','nam':'Свадебный'},
                {'imag':'54882693_2.jpg','nam':'Десерты'},
                {'imag':'54712265_3.jpg','nam':'Рулетики'},]
    return render(request, 'shop/home.html', locals(),)

def oplata(request):
    categories = Category.objects.all()
    return render(request, 'shop/include/oplata.html', locals())

def contacts(request):
    categories = Category.objects.all()
    return render(request, 'shop/include/contacts.html', locals())

django_pet_project/shop/templates/shop/include/about_our_work.html
{% load static %}
<div class="section section--u-idtceyv06" id="idtceyv06_0"
    data-do-section="{&quot;screen&quot;:{&quot;scroll&quot;:false,&quot;smooth&quot;:true}}">
    <div class="imageFit imageFit--u-i2ssposmc photo-swipe-image-nc" id="i2ssposmc_0"
        data-do-image="{&quot;screen&quot;:{&quot;objectFit&quot;:&quot;contain&quot;,&quot;lockRatio&quot;:true}}">
        <img src="{% static 'images/bez_nazvaniya_2.svg' %}" alt="Без названия 2" title=""
            class="imageFit__img imageFit__img--u-ib6l4xx9j" id="ib6l4xx9j_0">
        <div class="imageFit__overlay imageFit__overlay--u-ix5q66iig" id="ix5q66iig_0"></div>
        <div class="imageFit__zoom imageFit__zoom--u-ivdtn6w2x" id="ivdtn6w2x_0">
            <span class="svg_image svg_image--u-iyzaayq0f" id="iyzaayq0f_0"
                data-do-svg_image="{&quot;screen&quot;:{&quot;stretch&quot;:true}}">

            </span>
        </div>
    </div>
    <div class="container container--u-itn5jteu7" id="itn5jteu7_0">
        <div class="div div--u-i57ezkjo9" id="i57ezkjo9_0">
            <h1 class="page-title page-title--u-ir8x08r7e" id="ir8x08r7e_0">
                О нас и нашей работе
            </h1>
            <div class="text text--u-i5c00iat7" id="i5c00iat7_0">
                <span class="text-block-wrap-div">Проверены временем, воодушевлены работой </span>
            </div>
            <div class="rich-text rich-text--u-ivp3aykki" id="ivp3aykki_0">
                <div class="text-block-wrap-div">Все люди хоть немного, но сладкоежки, каждый порой балует себя
                    лакомствами, а чтобы отказать себе в сладостях, особенно по случаю какого-либо праздника, нужно
                    обладать поистине стоическим характером. Мы же не призываем Вас отказываться от лакомств, а наоборот
                    - предлагаем Вам обилие тортов и изготовление тортов на заказ.</div>
            </div>


           

            {% include 'contact_form/contact_form.html' %}

            


        </div>
    </div>
</div>

django_pet_project/shop/templates/shop/include/category.html
<div class="section section--u-irwdh9rff" id="irwdh9rff_0"
    data-do-section="{&quot;screen&quot;:{&quot;scroll&quot;:false,&quot;smooth&quot;:true}}">
    <div class="container container--u-i6k43wd8g" id="i6k43wd8g_0">
        <div class="div div--u-ivc0m2ox3" id="ivc0m2ox3_0">
            <div class="heading heading--u-i50hbrrn7" id="i50hbrrn7_0">
                <span class="text-block-wrap-div">У нас вы можете заказать</span>
            </div>
            <div class="text text--u-icpci4k9t" id="icpci4k9t_0">
                <span class="text-block-wrap-div">от простых пирожных до больших свадебных тортов</span>
            </div>
        </div>

        <div class="container container--u-i6k43wd8g" id="i6k43wd8g_0">
            <div class="list list--u-icqaob7gz" id="icqaob7gz_1">

                {% for category in categories reversed %}

                <div class="list__item list__item--u-ihcjmg3bn" id="ihcjmg3bn_1">
                    <div class="div div--u-i9g0h46xr" id="i9g0h46xr_1">
                        <div class="imageFit imageFit--u-i74lvrmm1 photo-swipe-image-nc" id="i74lvrmm1_1"
                            data-do-image="{&quot;screen&quot;:{&quot;objectFit&quot;:&quot;cover&quot;,&quot;lockRatio&quot;:true}}">
                            <a href="{{ category.slug }}"><img src="media/{{ category.images }}" alt="tort" title=""
                                    class="imageFit__img imageFit__img--u-ixz7l6d3d" id="ixz7l6d3d_1"></a>
                            <div class="imageFit__overlay imageFit__overlay--u-i1oj0413a" id="i1oj0413a_1"></div>
                            <div class="imageFit__zoom imageFit__zoom--u-i6yv3gcdv" id="i6yv3gcdv_1">
                                <span class="svg_image svg_image--u-igayz90qg" id="igayz90qg_1"
                                    data-do-svg_image="{&quot;screen&quot;:{&quot;stretch&quot;:true}}">
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="text text--u-iz9vdy4ci" id="iz9vdy4ci_1">
                        <span class="text-block-wrap-div">{{ category.name }}</span>
                    </div>
                    <div class="div div--u-i6n7c7i11" id="i6n7c7i11_1">
                        <div class="text text--u-iaq1cbwxx" id="iaq1cbwxx_1">
                            <span class="text-block-wrap-div">от</span>
                        </div>
                        <div class="text text--u-i85rqgh48" id="i85rqgh48_1">
                            <span class="text-block-wrap-div">{{ category.pris }}</span>
                        </div>
                        <div class="text text--u-itvspcgj6" id="itvspcgj6_1">
                            <span class="text-block-wrap-div">руб.</span>
                        </div>
                    </div>
                    <a href="{{ category.slug }}" class="link-universal link-universal--u-isast6g34" id="isast6g34_1"
                        data-do-link_universal="{&quot;screen&quot;:{&quot;type&quot;:&quot;link&quot;,&quot;popup&quot;:&quot;iddbgru7v_0&quot;,&quot;sidepanel&quot;:false,&quot;eventName&quot;:&quot;none&quot;,&quot;eventElement&quot;:&quot;self&quot;,&quot;eventAction&quot;:&quot;&quot;,&quot;selectedTag&quot;:&quot;&quot;,&quot;linkType&quot;:&quot;link&quot;,&quot;blank&quot;:false}}">
                        <div class="text text--u-i0oh2xm42" id="i0oh2xm42_1">
                            <span class="text-block-wrap-div">Перейти</span>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <a href="list" class="link-universal link-universal--u-icrph0do5" id="icrph0do5_0"
                data-do-link_universal="{&quot;screen&quot;:{&quot;type&quot;:&quot;link&quot;,&quot;popup&quot;:&quot;none&quot;,&quot;sidepanel&quot;:false,&quot;eventName&quot;:&quot;none&quot;,&quot;eventElement&quot;:&quot;self&quot;,&quot;eventAction&quot;:&quot;&quot;,&quot;selectedTag&quot;:&quot;&quot;,&quot;linkType&quot;:&quot;link&quot;,&quot;blank&quot;:false}}">
                <div class="text text--u-icolxarzs" id="icolxarzs_0">
                    <span class="text-block-wrap-div">Посмотреть весь каталог</span>
                </div>
            </a>
        </div>
    </div>
</div>

django_pet_project/shop/templates/shop/include/contacts.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
О НАС
{% endblock %}

{% block content %}

<h1>КОНТАКТЫ</h1>
<h2>МЫ ВСЕГДА НА СВЯЗИ </h2>
<h3>
   <p>- тел : +7 0000000000 </p>
</h3>
<h3>
   <p>- email: admin@django-pet-project.ru </p>
</h3>

{% endblock %}

django_pet_project/shop/templates/shop/include/footer.html
<footer class="footer" style="background-color: rgb(120, 6, 148);">

    <div class="row">
        <div class="col-6 col-md-3 mb-3" style="padding-left: calc(var(--bs-gutter-x) * .8); margin-top: 0.9em;">
            <h4> ИНФОРМАЦИЯ</h4>
            <ul class="nav flex-column">
                <li><a href="{% url 'shop:home' %}"> ГЛАВНАЯ</a></li>
                <li><a href="{% url 'shop:contacts' %}"> КОНТАКТЫ</a></li>
                <li><a href="{% url 'shop:oplata' %}"> ОПЛАТА И ДОСТАВКА</a></li>
            </ul>
        </div>

        <div class="col-6 col-md-3 mb-3" style="margin-top: 0.9em;">
            <h4>ВРЕМЯ РАБОТЫ</h4>
            <ul class="nav flex-column">
                <li>г. ТАГАНРОГ</li>
                <li>Пн-Вс</li>
                <li>С 7:00 ДО 20:00</li>
                <li>БЕЗ ПЕРЕРЫВОВ</li>
            </ul>
        </div>

        <div class="col-6 col-md-3 mb-3" style="padding-left: calc(var(--bs-gutter-x) * .8); margin-top: 0.9em;">
            <h4>КОНТАКТЫ</h4>
            <ul class="nav flex-column">
                <li><a href="tel:89920457602">ТЕЛЕФОН +7 0000000000</a></li>
                <li><a href="mail:admin@django-pet-project.ru">Email: admin@django-pet-project.ru</a></li>
                <li><a href="{% url 'feedback:feedback_form' %}">ОБРАТНАЯ СВЯЗЬ</a></li>
            </ul>
        </div>

        <div class="col-6 col-md-3 mb-3" style="margin-top: 0.9em;">
            <h4>МЫ В СЕТИ</h4>
            <ul class="nav flex-column"></ul>
            <li><a href="#"><i class="fa-brands fa-vk"></i></a></li>
            </ul>
        </div>

    </div>
</footer>

django_pet_project/shop/templates/shop/include/foto.html
{% load static %}
<div class="section section--u-ifnb54wrw" id="ifnb54wrw_0"
  data-do-section="{&quot;screen&quot;:{&quot;scroll&quot;:false,&quot;smooth&quot;:true}}">
  <div class="imageFit imageFit--u-iv8mktuk4 photo-swipe-image-nc" id="iv8mktuk4_0"
    data-do-image="{&quot;screen&quot;:{&quot;objectFit&quot;:&quot;contain&quot;,&quot;lockRatio&quot;:true}}">
    <img src="{% static 'images/gallery2.png' %}" alt="Gallery2" title=""
      class="imageFit__img imageFit__img--u-ignl9sb85" id="ignl9sb85_0">
    <div class="imageFit__overlay imageFit__overlay--u-i9agx354j" id="i9agx354j_0"></div>
    <div class="imageFit__zoom imageFit__zoom--u-idbvscb4d" id="idbvscb4d_0">
      <span class="svg_image svg_image--u-iudsgs18p" id="iudsgs18p_0"
        data-do-svg_image="{&quot;screen&quot;:{&quot;stretch&quot;:true}}">

      </span>
    </div>
  </div>
  <div class="container container--u-iyp6rym6u" id="iyp6rym6u_0">
    <div class="div div--u-i06jka86v" id="i06jka86v_0">
      <div class="heading heading--u-i7knlmoqi" id="i7knlmoqi_0">
        <span class="text-block-wrap-div">Посмотрите на наши работы</span>
      </div>
      <div class="text text--u-izgwae5xl" id="izgwae5xl_0">
        <span class="text-block-wrap-div">Наша продукция (сласти, сладости, сладкие блюда) - высококалорийные и
          легкоусваиваемые пищевые продукты с большим содержанием сахара, отличающиеся приятным вкусом и
          ароматом.</span>
      </div>
    </div>
  </div>
  <div class="list list--u-in0ffulxc" id="in0ffulxc_0">

    {% for data in list_foto %}

    <div class="list__item list__item--u-i2rbz5wz3" id="i2rbz5wz3_5">
      <div class="imageFit imageFit--u-i6tsask43 photo-swipe-image-nc cursor-pointer" id="i6tsask43_5"
        data-do-image="{&quot;screen&quot;:{&quot;objectFit&quot;:&quot;cover&quot;,&quot;lockRatio&quot;:true,&quot;maxHeight&quot;:1920,&quot;maxWidth&quot;:1920,&quot;zoomOnClick&quot;:true,&quot;scrollZoom&quot;:true}}">

        <img src="static/images/{{ data.imag }}" alt="54856384_2" title=""
          class="imageFit__img imageFit__img--u-imetyexti" id="imetyexti_5">

        <div class="imageFit__overlay imageFit__overlay--u-iwx7z4jz4" id="iwx7z4jz4_5">
          <div class="text text--u-i86yf1xsh" id="i86yf1xsh_5">
            <span class="text-block-wrap-div">{{ data.nam }}</span>
          </div>
          <span class="svg_image svg_image--u-il0x8qz8n" id="il0x8qz8n_5"
            data-do-svg_image="{&quot;screen&quot;:{&quot;stretch&quot;:true}}">

            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
              <svg xmlns="http://www.w3.org/2000/svg" width="22.844" height="23.219" viewBox="0 0 22.844 23.219"
                data-prefix="ia1nzjzwo">
                <path
                  d="M22.541 22.937a1 1 0 0 1-1.414 0l-5.091-5.088a9.982 9.982 0 1 1 1.454-1.373l5.051 5.048a1 1 0 0 1 0 1.413zM9.955 2a7.966 7.966 0 1 0 7.97 7.968A7.982 7.982 0 0 0 9.955 2zM4.348 9.965h-1a6.614 6.614 0 0 1 6.607-6.6v1a5.613 5.613 0 0 0-5.607 5.603z"
                  fill-rule="evenodd" class="path-ida8cj9d1"></path>
              </svg>
            </button>

          </span>
        </div>

        <div class="imageFit__zoom imageFit__zoom--u-i1qe8weph" id="i1qe8weph_5">

          <span class="svg_image svg_image--u-i1wgkuryx" id="i1wgkuryx_5"
            data-do-svg_image="{&quot;screen&quot;:{&quot;stretch&quot;:true}}">
          </span>

        </div>

      </div>

    </div>
    {% endfor %}

  </div>
</div>





<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">НАША ПРОДУКЦИЯ </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
          {% for data in list_foto %}
          <div class="carousel-inner">

            <div class="carousel-item active">
              <img src="static/images/{{ data.imag }}" class="d-block w-100" alt="{{ data.nam }}">
            </div>

          </div>
          {% endfor %}
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" color="black" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>



      </div>
      <div class="modal-footer">
        <!-- <input type="hidden" name="image" value="{{ data.imag }}"> -->
        <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

django_pet_project/shop/templates/shop/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #fa66c1;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'shop:home' %}">django-pet-project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:home' %}">ГЛАВНАЯ</a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:contacts' %}">КОНТАКТЫ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'feedback:feedback_form' %}">ОБРАТНАЯ СВЯЗЬ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'foto_gallery:foto_gallery' %}">ФОТОГАЛЕРЕЯ</a>
        </li>

      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item"></li>
        <a class="nav-link" href="tel:89920457602"> +7 0000000000 </a>

        <li class="nav-item dropdown"></li>
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"><i class="fa-regular fa-user">
            {% if user.is_authenticated %}
          </i><span class="navbar-text">
            Привет, {{ user.username }}!
          </span></a>
        {% else %}
        </i><span class="navbar-text">
          Привет, Гость!
        </span></a>
        {% endif %}
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.is_authenticated %}
          <li id="profile_link">
            <a href="{% url 'users:profile' %}?next={{request.path}}">
              <i class="fa fa-user-circle" aria-hidden="true"></i>
              Профиль
            </a>
          </li>
          <li id="logout_link">
            <a href="{% url 'logout' %}">
              <i class="fa fa-sign-out" aria-hidden="true"></i>
              Выход
            </a>
          </li>
          {% else %}
          <li>
            <a class="color_black" href="{% url 'login' %}">
              <i class="fa fa-sign-in icons" aria-hidden="true"></i>
              Войти
            </a>
          </li>
          <li>
            <a class="color_black" href="{% url 'users:register' %}">
              <i class="fa fa-user-plus icons" aria-hidden="true"></i>
              Регистрация
            </a>
          </li>
          {% endif %}
        </ul>
        </li>
        <li class="nav-item"></li>
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        <a class="nav-link" href="{% url 'cart:cart_detail' %}">
          <i class="fa-solid fa-cart-shopping"></i>
          Корзина:
          {{ total_items }} тов.
          <span class="cart_price">{{ cart.get_total_price }} руб.</span>
        </a>
        {% else %}
        <a class="nav-link" href="{% url 'cart:cart_detail' %}">
          <i class="fa-solid fa-cart-shopping"></i>
          Корзина пуста
        </a>
        {% endif %}
        {% endwith %}
        </li>
        



      </ul>

    </div>
  </div>
</nav>

django_pet_project/shop/templates/shop/include/oplata.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
ОПЛАТА И ДОСТАВКА
{% endblock %}

{% block content %}

<h1>ОПЛАТА И ДОСТАВКА</h1>
<h2>Доставку осуществляем на указанный адресс по предварительной договорённости </h2>
<h3>Оплата при получении</h3>
<h3>Либо любым удобным вам способом</h3>


<h2>МЫ ВСЕГДА НА СВЯЗИ </h2>
<h3>
   <p>- тел : +7 0000000000 </p>
</h3>
<h3>
   <p>- email: admin@django-pet-project.ru </p>
</h3>

{% endblock %}