django_pet_project/cart/urls.py
from django.urls import path


from . views import (
    cart_add,
    cart_detail,
    cart_remove
)


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

django_pet_project/django_pet_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django_pet_project import settings
from cart import views
from shop import views
from users import views as user_views
from contact_form.views import create


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact_form/', include('contact_form.urls', namespace='contact_form')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('foto_gallery/', include('foto_gallery.urls', namespace='foto_gallery')),
    path('', include('shop.urls')),
    
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_pet_project/feedback/urls.py
from django.urls import path


from .views import create, feedback_form


app_name = 'feedback'

urlpatterns = [
    path('feedback_form', feedback_form, name='feedback_form'),
    path('feedback', create, name='feedback'),
    
]

django_pet_project/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop.views import (
    product_list, 
    product_detail,
    home,   
    oplata,
    contacts,
)

app_name = 'shop'

urlpatterns = [
    path('',home, name='home'),
    path('list', product_list, name='product_list'),
    path('<str:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('oplata', oplata, name='oplata'),
    path('contacts', contacts, name='contacts'),
    


]


# path('', views.product_list, name='product_list'),
#     path('elasticsearch_results/', ElasticSearchView.as_view(), name='elasticsearch'),
#     path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<str:brand_slug>', views.brands_views, name='brands_views'),
#     path('<str:id>/<str:slug>/', views.product_detail, name='product_detail'),
# path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<str:brand_slug>', views.brands_views, name='brands_views'),
#     path('<str:id>/<str:slug>/', views.product_detail, name='product_detail'),


# urlpatterns = [
#     url(r'^$', views.product_list, name='product_list'),
#     url(r'^(?P<category_slug>[-\w]+)/$',
#         views.product_list,
#         name='product_list_by_category'),
#     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
#         views.product_detail,
#         name='product_detail'),
# ]

django_pet_project/feedback/models.py
from django.db import models


class Feedback(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.TextField(max_length=1000)
    created_it = models.DateTimeField(auto_now_add=True) 

    class Meta:
        verbose_name = 'Обратная_связь'
        verbose_name_plural = 'Обратная_связь'


    def __str__(self):
        # Будет отображаться следующее поле в панели администрирования
        return self.email

django_pet_project/feedback/views.py
from .models import Feedback
from django.conf import settings
from django.http import HttpResponse
from django.core.mail import get_connection, EmailMultiAlternatives
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound


def create(request):
    if request.method == "POST":
       # Сохраняем в базу
        data_model = Feedback()
        data_model.first_name = request.POST.get("first_name")
        data_model.last_name = request.POST.get("last_name")
        data_model.email = request.POST.get("email")
        data_model.message = request.POST.get("message")
        data_model.save()
        # Формируем сообщение для отправки
        subject = f'Сообщение с формы от {data_model.first_name} {data_model.last_name} Почта отправителя: {data_model.email}'
        email(subject, data_model.message)
        return render(request, 'feedback/succes.html', locals())


# Функция отправки сообщения
def email(subject, content):
    connection = get_connection()
    connection.open()
    msg = EmailMultiAlternatives(subject, content,
                                 settings.EMAIL_HOST_USER, ['admin@django-pet-project.ru'],
                                 connection=connection)
    msg.send()
    connection.close()  # Cleanup
    

def feedback_form(request):
    return render(request, 'feedback/feedback.html', locals())


     

django_pet_project/feedback/templates/feedback/feedback.html
{% extends 'shop/base.html' %}
{% block title %}

ОБРАТНЯ СВЯЗЬ
{% endblock %}

{% block content %}
<style>
   * {
      box-sizing: border-box;
   }

   body {
      background: #f673d4;
   }

   .decor {
      position: relative;
      max-width: 400px;
      margin: 50px auto 0;
      background: white;
      border-radius: 30px;
   }

   .form-left-decoration,
   .form-right-decoration {
      content: "";
      position: absolute;
      width: 50px;
      height: 20px;
      background: #f673d4;
      border-radius: 20px;
   }

   .form-left-decoration {
      bottom: 60px;
      left: -30px;
   }

   .form-right-decoration {
      top: 60px;
      right: -30px;
   }

   .form-left-decoration:before,
   .form-left-decoration:after,
   .form-right-decoration:before,
   .form-right-decoration:after {
      content: "";
      position: absolute;
      width: 50px;
      height: 20px;
      border-radius: 30px;
      background: white;
   }

   .form-left-decoration:before {
      top: -20px;
   }

   .form-left-decoration:after {
      top: 20px;
      left: 10px;
   }

   .form-right-decoration:before {
      top: -20px;
      right: 0;
   }

   .form-right-decoration:after {
      top: 20px;
      right: 10px;
   }

   .circle {
      position: absolute;
      bottom: 80px;
      left: -55px;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: white;
   }

   .form-inner {
      padding: 50px;
   }

   .form-inner input,
   .form-inner textarea {
      display: block;
      width: 100%;
      padding: 0 20px;
      margin-bottom: 10px;
      background: #E9EFF6;
      line-height: 40px;
      border-width: 0;
      border-radius: 20px;
      font-family: 'Roboto', sans-serif;
   }

   .form-inner input[type="submit"] {
      margin-top: 30px;
      background: #f69a73;
      border-bottom: 4px solid #d87d56;
      color: white;
      font-size: 14px;
   }

   .form-inner textarea {
      resize: none;
   }

   .form-inner h3 {
      margin-top: 0;
      font-family: 'Roboto', sans-serif;
      font-weight: 500;
      font-size: 24px;
      color: #707981;
   }
</style>
<form action="{% url 'feedback:feedback'%}" method="POST">
   {% csrf_token %}
   <form class="decor">
      <div class="form-left-decoration"></div>
      <div class="form-right-decoration"></div>
      <div class="circle"></div>
      <div class="form-inner">
         <h3>Написать нам</h3>
         <input type="text" name="first_name" placeholder="Иван">
         <input type="text" name="last_name" placeholder="Иванов">
         <input type="email" name="email" placeholder="exempl@email.ru">
         <textarea name="message" placeholder="Сообщение..." rows="3"></textarea>
         <input type="submit" value="Отправить">
      </div>
   </form>

</form>

<form action="{% url 'shop:home' %}">

   <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Главная</button>
</form>
{% endblock %}

django_pet_project/feedback/templates/feedback/succes.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}

Сообщение отправленно
{% endblock %}

{% block content %}

<h1>Ваше сообщение отправленно</h1>

<p>
<h2>Мы рады обратной связи с вами </h2>
</p>


<!-- <input type="hidden" name="image" value="{{ data.imag }}"> -->
<form action="{% url 'shop:home' %}">

  <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Главная</button>
</form>
{% endblock %}