django_pet_project/cart/urls.py
from django.urls import path


from . views import (
    cart_add,
    cart_detail,
    cart_remove
)


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

django_pet_project/django_pet_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django_pet_project import settings
from cart import views
from shop import views
from users import views as user_views
from contact_form.views import create


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('contact_form/', include('contact_form.urls', namespace='contact_form')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('foto_gallery/', include('foto_gallery.urls', namespace='foto_gallery')),
    path('', include('shop.urls')),
    
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_pet_project/users/urls.py
from django.urls import include, path

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('page_ordered_goods/', views.page_ordered_goods,
         name='page_ordered_goods'),
    path('change_phone_or_image/', views.change_phone_or_image,
         name='change_phone_or_image'),
]

django_pet_project/users/models.py
from django.db import models
from django.contrib.auth.models import User
import io
from django.core.files.storage import default_storage as storage

# from phonenumber_field.modelfields import PhoneNumberField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                verbose_name="Пользователь")
    phone = models.CharField(max_length=50, verbose_name="Телефон")


    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

django_pet_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1',
                  'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone']

django_pet_project/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

from orders.models import Order


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Ваш аккаунт создан! " f"{username} теперь вы можете войти."
            )
            return redirect("login")
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form": form})


@login_required
def profile(request):
    return render(request, "users/profile.html")


@login_required
def change_phone_or_image(request):
    if request.method == "POST":
        # u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if p_form.is_valid():  # and u_form.is_valid():
            # u_form.save()
            p_form.save()
            messages.success(request, f"Ваш аккаунт обновлен!")
            return redirect("users:profile")
    else:
        # u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        # 'u_form': u_form,
        "p_form": p_form,
    }

    return render(request, "users/change_phone_or_image.html", context)


@login_required
def page_ordered_goods(request):
    user_orders = Order.objects.filter(email=request.user.email)
    orders = []
    for i in range(len(user_orders)):
        orders.append(get_object_or_404(Order, id=user_orders[i].id))
    context = {"orders": orders}
    return render(request, "users/page_ordered_goods.html", context)

django_pet_project/users/templates/users/change_phone_or_image.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <h3 class="back_button">
    <a href="{{request.META.HTTP_REFERER}}">Назад</a>
  </h3>
  <h4 class="img_phone_instructions">
    Добавьте или измените номер телефона
  </h4>
  <div class="profile_wrapper">
    <div>
      <div>
        <h3 class="profile_username">{{ user.username }}</h3>
      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group phone_img_form">
        {{ p_form|crispy}}
      </fieldset>
      <div class="form-group button_section">
        <button class="button_base blue_button" type="submit">Обновить</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

django_pet_project/users/templates/users/page_ordered_goods.html
{% extends "shop/base.html" %}

{% load static %}
{% block content %}
<div class="content-section">
  <h3 class="back_button">
    <a href="{{request.META.HTTP_REFERER}}">Назад</a>
  </h3>
  <h4 class="goods_title">Список заказов</h4>
  <table class="goods_table">
    <h3 class="goods_title">Заказанные товары</h3>
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Название товара</th>
        <th>Кол.</th>
        <th>Дата заказа</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      {% for item in order.items.all %}
      <tr class="row{% cycle '1' '2' %}">
        <td>
          <a href="{{ item.product.get_absolute_url }}">
            <img src="{% if item.product.image %}
                            {{ item.product.image.url }}{% else %}
                            {% static 'images/no-image.jpeg'%}{% endif %}">
          </a>
        </td>
        <td>{{ item.product.name }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.order.created }}</td>
      </tr>
      {% endfor %}
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

django_pet_project/users/templates/users/profile.html
{% extends "shop/base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <h3 class="page_title">Информация о профиле</h3>
  <div class="profile_wrapper">
    <div class="profile_content">
      <h2>{{ user.username }}</h2>
      <p>{{ user.email }}</p>
      <p>{{ user.first_name }}</p>
      <p>{{ user.last_name }}</p>
      <p>{{ user.profile.phone }}</p>
    </div>
  </div>
  <div class="profile_links">
    <a href="{% url 'users:page_ordered_goods' %}">
      <i class="fa fa-sort" aria-hidden="true"></i>
      Страница заказов
    </a>
  </div>
  <div class="profile_links">
    <a href="{% url 'users:change_phone_or_image' %}">
      <i class="fa fa-cog" aria-hidden="true"></i>
      Добавьте или измените номер телефона
    </a>
  </div>
</div>
{% endblock content %}

django_pet_project/users/templates/users/register.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}

{% block title %}
{% endblock %}

{% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend>Присоеденяйтесь сегодня</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group button_section">
      <button class="button_base blue_button" type="submit">
        Зарегистрироваться
      </button>
    </div>
  </form>
  <div class="req_login_section">
    <small class="text-muted">
      Уже есть аккаунт? <a href="{% url 'login' %}" class="ml">Войти</a>
    </small>
  </div>
</div>
{% endblock content%}